// Descriptions for each career shown on results. Keep separate from careerProfiles
// so scoring stays purely trait-driven.
export const careerDescriptions: Record<string, string> = {
  "Software Engineer": "Design, build, and maintain software systems that solve real-world problems.",
  "Data Scientist": "Turn complex data into insights that guide strategy and decisions.",
  "UX Designer": "Craft intuitive, human-centered digital experiences.",
  "Product Manager": "Set product vision and coordinate teams to ship what customers need.",
  "Marketing Specialist": "Create campaigns that connect brands with the right audiences.",
  "Sales Executive": "Build client relationships and drive revenue through consultative selling.",
  "HR Manager": "Shape culture and support people throughout their career journey.",
  "Financial Analyst": "Analyze financial data to inform investments and business decisions.",
  "Operations Manager": "Optimize processes and lead teams to run reliably at scale.",
  "Business Consultant": "Advise organizations on strategy, transformation, and growth.",
  "Teacher/Educator": "Guide learners, design curricula, and inspire lasting curiosity.",
  "Healthcare Professional": "Care for patients and communities with skill and empathy.",
  "Research Scientist": "Advance knowledge through rigorous experimentation and inquiry.",
  "Entrepreneur": "Turn ideas into ventures and build something from the ground up.",
  "Project Manager": "Lead cross-functional projects to deliver outcomes on time.",
  "Architect": "Design buildings and spaces that balance beauty, function, and structure.",
  "Civil Engineer": "Plan and build the infrastructure that shapes modern life.",
  "Lawyer": "Advocate, advise, and interpret the law with precision.",
  "Journalist": "Investigate stories and communicate them clearly to the public.",
  "Graphic Designer": "Communicate ideas visually across brands, products, and media.",
  "Cybersecurity Analyst": "Protect systems and data from evolving threats.",
  "Supply Chain Manager": "Orchestrate logistics so the right things reach the right places.",
  "Customer Success Manager": "Ensure customers thrive with the product long after the sale.",
  "AI/ML Engineer": "Build intelligent systems that learn from data.",
  "Public Relations Officer": "Shape narrative and manage relationships with the public.",
};
